"""cria tabela partida

Revision ID: 328a371f5724
Revises: 
Create Date: 2026-10-03 13:16:55.946384

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '328a371f5724'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partida',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=4), nullable=False),
    sa.Column('modo', sa.String(length=20), nullable=False),
    sa.Column('palavra_secreta', sa.String(length=5), nullable=False),
    sa.Column('jogador1_nome', sa.String(length=24), nullable=False),
    sa.Column('jogador2_nome', sa.String(length=24), nullable=False),
    sa.Column('jogador1_pontos', sa.Integer(), nullable=False),
    sa.Column('jogador2_pontos', sa.Integer(), nullable=False),
    sa.Column('vencedor_nome', sa.String(length=24), nullable=True),
    sa.Column('criada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalizada_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partida_codigo'), 'partida', ['codigo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_partida_codigo'), table_name='partida')
    op.drop_table('partida')
    # ### end Alembic commands ###
